name: Tests
on: [push, pull_request]
permissions: read-all
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: simulate-test-failure
        run: |
          set -euo pipefail

          ./scripts/test.sh
